### PR TITLE
chore(scripts): update scripts to extract *.ftl from fxa-settings

### PR DESCRIPTION
**Pull request by chenba**
Update scripts to extract *.ftl files from fxa-settings.

Please do not merge yet!  We'd like to have the one ftl file in fxa-setting reviewed before merging.

### CODE REVIEW

**Comment by peiying2** [comment]
@chenba please ping the person who needs to review this PR. I am not the right person to review this particular one.

**Comment by chenba** [comment]
@dannycoates r?

**Review by dannycoates — APPROVED** [review]
LGTM

**Comment by 6a68** [comment]
@chenba Hey, now that #466 has landed, is this also good to land?

**Comment by chenba** [comment]
> 
> 
> @chenba Hey, now that #466 has landed, is this also good to land?

Yep, I'll merge now.

**Pull request merged**
