### PR TITLE
Update server.po

### PR DESCRIPTION
**Pull request by thingdiputra**
update server.po

### CODE REVIEW

**Comment by jayvdb** [comment]
See https://github.com/mozilla/fxa-content-server-l10n#submitting-translations .

**Comment by vladikoff** [comment]
We have some translation teams submitting these as GitHub PRs. I do not think it matters to us how these are submitted, but does it matter to Pontoon @jayvdb ?

**Comment by jayvdb** [comment]
Yes. Pontoon doesnt support that yet. See [bug 1243101](https://bugzilla.mozilla.org/show_bug.cgi?id=1243101).

**Comment by thingdiputra** [comment]
I'm sorry. I was careless and didnt read the instruction properly. I will follow instruction about submitting translations.

**Pull request closed without merging**
