### PR TITLE
fix(server.po): recover email string translations

### PR DESCRIPTION
**Pull request by zaach**
@shane-tomlinson @mathjazz I've added the translations back and updated the template.

### CODE REVIEW

**Comment by mathjazz** [comment]
Looks good. Just a quick question. The following pairs are almost identical:

Reset password - Reset password:
Verify account - Verify account:
Verify - Verify:

Are they intentionally different or can we unify them?

**Comment by shane-tomlinson** [comment]
> Looks good. Just a quick question. The following pairs are almost identical:
>
> Reset password - Reset password:
> Verify account - Verify account:
> Verify - Verify:
> 
> Are they intentionally different or can we unify them?

@ryanfeeley - what do you think about some unification? "Verify account" and "Verify" seem reasonable.

@mathjazz - the colon is to separate the text from a verification link that follows. What is the best practice there?

**Comment by mathjazz** [comment]
OK, in this case "string - string:" pairs should be separate strings, as they could be different parts of speech (verb vs. noun).

**Comment by shane-tomlinson** [comment]
LGTM! @jrgm are these the strings that will be used for today's prod push?

**Comment by zaach** [comment]
The prod push is using an earlier hash– this will just affect deployments using fxa-dev.

**Comment by mathjazz** [comment]
That means some strings will be left untranslated after the new release or is this already the case in prod?

**Comment by zaach** [comment]
@mathjazz We're using this hash: 9b283e26aaead44ef6c4d1216b0a6d01f547399f, which has the email strings but won't have translations to strings made in the last 5 days. But that's usually the case.

**Comment by mathjazz** [comment]
OK. To make "that's usually the case" clear - we usually push to production first and give strings to localizers after that?

**Comment by zaach** [comment]
@mathjazz Yeah, actually I merge strings for train 32 earlier than necessary. We could wait and merge them after the current train is pushed to production. As it stands, localizers will have extra time for train 32.

**Comment by mathjazz** [comment]
Okay, thanks for explaining this @zaach!

**Comment by jrgm** [comment]
Slightly off-topic, but about L10N and production releases, I wrote this micro-note on how the rpm is built with a specific version of fxa-content-server-l10n (default is HEAD). https://github.com/mozilla-services/svcops/blob/master/services/firefox-accounts/fxa-content-server/README.md

**Comment by shane-tomlinson** [comment]
@zaach - it looks like this rebased or done again. A few commits came in after this PR was created and a clean merge is no longer possible.

**Comment by zaach** [comment]
Rebased.

**Comment by shane-tomlinson** [comment]
Thanks @zaach, @mathjazz, what do you think, can we hit "merge"?

**Comment by mathjazz** [comment]
Let's hit the merge!

**Comment by zaach** [comment]
Merging :+1:

**Comment by mathjazz** [comment]
Verbatim updated.

But -- it seems like some locales aren't in sync with the templates:
https://localize.mozilla.org/projects/accounts/

(Sort by "Total".)

**Comment by zaach** [comment]
@mathjazz Thanks, I've opened another PR. Not sure how those didn't make it into the initial train 32 PR.

**Pull request merged**
