### PR TITLE
merge strings for train 11221

### PR DESCRIPTION
**Pull request by bug-mirror**

### CODE REVIEW

**Comment by vladikoff** [comment]
Done in https://github.com/mozilla/fxa-content-server-l10n/pull/257

**Comment by TonnesM** [comment]
"Scan the QR code in your app and confirm it is setup correctly …"

Shouldn’t that be "set up"?

Additionally, localizers may wonder what "it" applies to (either the two-factor authentication, the app, or even the QR code).

**Comment by vladikoff** [comment]
cc @ryanfeeley @vbudhram

**Comment by ryanfeeley** [comment]
"set up" is correct.

**Pull request closed without merging**
