### PR TITLE
[pt-PT] Translation updates for (European) Portuguese

### PR DESCRIPTION
**Pull request by cesperanc**

### CODE REVIEW

**Comment by shane-tomlinson** [comment]
Hi @cesperanc - this PR is now out of date and needs to be rebased.

**Comment by cesperanc** [comment]
Can you merge this or did I mess it up?

**Comment by vladikoff** [comment]
> Can you merge this or did I mess it up?

You need to rebase it against the master branch

**Comment by cesperanc** [comment]
Please ignore this pull request... I've created PR #79 to merge this changes.

**Pull request closed without merging**
