### PR TITLE
merged server strings for train 45

### PR DESCRIPTION
**Pull request by dannycoates**
Contains the new email strings for https://github.com/mozilla/fxa-auth-mailer/pull/72

### CODE REVIEW

**Comment by vladikoff** [comment]
Conflicts! :scream:

**Comment by dannycoates** [comment]
moving target :dart:

**Comment by mathjazz** [comment]
Hey, just checking why these strings got merged without a notice? Updating Verbatim...

@dannycoates @zaach

**Comment by mathjazz** [comment]
I'd suggest against putting this into localizable strings, because it's confusing localizers, some of them will translate these words:
<a href='%(supportUrl)s' style='color: #0095dd; text-decoration: none;'>

Also, do we really need all these string:
- Activate Now
- Activate now
- Activate now:

**Comment by rfk** [comment]
> some of them will translate these words

@mathjazz do you mean the "style" declarations specifically?

**Comment by mathjazz** [comment]
@rfk I mean we should simply use something like this instead:
```For more information, please visit <a %(supportUrl)s>Mozilla Support</a>```

Less markup means less possibilities for localizers to break stuff. ;)

Also, we already have this string:
```For more information, please visit %(supportUrl)s```

**Comment by zaach** [comment]
Perhaps we can do something clever like `For more information, please visit <a %(linkAttributes)s>Mozilla Support</a>` and inject all of the attributes rather than just the URL.

The problem with reusing `For more information, please visit %(supportUrl)s` is that it doesn't include `Mozilla Support`, which I suppose may affect how it is translated.

**Pull request merged**
