### PR TITLE
new strings for train 26

### PR DESCRIPTION
**Pull request by zaach**
@mathjazz Let me know when we're ready to merge! Thanks.

### CODE REVIEW

**Comment by zaach** [comment]
Blah. Forgot to merge this. Rebasing.

**Comment by zaach** [comment]
@mathjazz Somehow this PR got lost in the wind. Okay to merge now?

**Comment by mathjazz** [comment]
Yeah, you're still good to go.

**Comment by mathjazz** [comment]
Verbatim updated for all locales.

**Pull request merged**
