### PR TITLE
Add Kazakh (kk) translation.

### PR DESCRIPTION
**Pull request by crayxt**
Added initial Kazakh translation.

### CODE REVIEW

**Comment by seanmonstar** [comment]
@mathjazz whats the proper procedure with these?

**Comment by rfk** [comment]
> whats the proper procedure with these?

In particular, do you want these to come in via pontoon rather than as standalone PRs?

**Comment by mathjazz** [comment]
We suggest localizers to use our tools (e.g. Pontoon), because permission system, quality checks, translation memory and such.

That being said, Baurzhan is our kk localizer, so this is r+. You can usually check if PR is safe to take by looking at the L10n team wiki (https://wiki.mozilla.org/L10n:Teams:kk).

**Comment by shane-tomlinson** [comment]
Thanks for the quick response @mathjazz, merged.

**Pull request merged**
